version: '3.5'
services:
  rss:
    container_name: rss
    build: ../../
    image: aaronysj/rss:1.1.1
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure:5

networks:
  default:
    external:
      name: rss_net
