version: '3.5'
services:
  redis:
    container_name: rss_redis
    image: redis
    command: redis-server --requirepass gxfc --appendonly yes
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
    networks:
      - appnet
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.25-management
    networks:
      - appnet
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rss
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=gxfc
      - RABBITMQ_DEFAULT_VHOST=aaronysj
      - TZ=Asia/Shanghai
  rss:
    container_name: rss
    build: .
    image: aaronysj/rss:@image_tag@
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8080:8080
    networks:
      - appnet
    restart: on-failure:5

networks:
  appnet:
