version: "3.5"

services:
  nginx:
    image: nginx:1.20.1-alpine
    container_name: nginx
    restart: always
    ports:
      - 10443:10443
    hostname: nginx
    volumes:
      - ./:/etc/nginx

networks:
  default:
    external:
      name: rss_net